// Bundled Registry Objects for instant 100% reliable execution in Windows
// Includes all registry tweaks with MouseHoverTime = Hexadecimal 29 (DWORD 0x00000029 / 41 ms)

const commonLatencyKeys = [
  { path: 'HKCU\\Control Panel\\Mouse', name: 'MouseHoverTime', type: 'REG_DWORD', value: 41 },
  { path: 'HKU\\.DEFAULT\\Control Panel\\Mouse', name: 'MouseHoverTime', type: 'REG_DWORD', value: 41 },
  { path: 'HKCU\\Control Panel\\Accessibility\\MouseKeys', name: 'Flags', type: 'REG_SZ', value: '0' },
  { path: 'HKCU\\Control Panel\\Accessibility\\StickyKeys', name: 'Flags', type: 'REG_SZ', value: '0' },
  { path: 'HKCU\\Control Panel\\Accessibility\\ToggleKeys', name: 'Flags', type: 'REG_SZ', value: '0' },
  { path: 'HKCU\\Control Panel\\Accessibility\\Keyboard Response', name: 'Flags', type: 'REG_SZ', value: '0' },
  { path: 'HKCU\\Control Panel\\Accessibility\\Keyboard Response', name: 'DelayBeforeAcceptance', type: 'REG_SZ', value: '0' },
  { path: 'HKCU\\Control Panel\\Accessibility\\Keyboard Response', name: 'AutoRepeatDelay', type: 'REG_SZ', value: '200' },
  { path: 'HKCU\\Control Panel\\Accessibility\\Keyboard Response', name: 'AutoRepeatRate', type: 'REG_SZ', value: '15' },
  { path: 'HKLM\\SYSTEM\\CurrentControlSet\\Services\\mouclass\\Parameters', name: 'MouseDataQueueSize', type: 'REG_DWORD', value: 20 },
  { path: 'HKLM\\SYSTEM\\CurrentControlSet\\Services\\mouclass\\Parameters', name: 'MouseResolution', type: 'REG_DWORD', value: 1 },
  { path: 'HKLM\\SYSTEM\\CurrentControlSet\\Services\\mouclass\\Parameters', name: 'MouseTicks', type: 'REG_DWORD', value: 1 },
  { path: 'HKLM\\SYSTEM\\CurrentControlSet\\Services\\kbdclass\\Parameters', name: 'KeyboardDataQueueSize', type: 'REG_DWORD', value: 20 },
  { path: 'HKLM\\SYSTEM\\CurrentControlSet\\Services\\kbdclass\\Parameters', name: 'KeyboardResolution', type: 'REG_DWORD', value: 1 },
  { path: 'HKLM\\SYSTEM\\CurrentControlSet\\Services\\kbdclass\\Parameters', name: 'KeyboardTicks', type: 'REG_DWORD', value: 1 },
  { path: 'HKLM\\SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Multimedia\\SystemProfile', name: 'SystemResponsiveness', type: 'REG_DWORD', value: 0 },
  { path: 'HKLM\\SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Multimedia\\SystemProfile', name: 'NetworkThrottlingIndex', type: 'REG_DWORD', value: 4294967295 },
  { path: 'HKLM\\SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Multimedia\\SystemProfile\\Tasks\\Games', name: 'Priority', type: 'REG_DWORD', value: 6 },
  { path: 'HKLM\\SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Multimedia\\SystemProfile\\Tasks\\Games', name: 'GPU Priority', type: 'REG_DWORD', value: 8 },
  { path: 'HKLM\\SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Multimedia\\SystemProfile\\Tasks\\Games', name: 'Scheduling Category', type: 'REG_SZ', value: 'High' },
  { path: 'HKLM\\SYSTEM\\CurrentControlSet\\Services\\Tcpip\\Parameters', name: 'TCPNoDelay', type: 'REG_DWORD', value: 1 }
];

module.exports = {
  'regedit-do-flash': {
    name: 'Regedit do Flash',
    fix: 'Flash 1.0',
    keys: [
      { path: 'HKCU\\Control Panel\\Mouse', name: 'Active', type: 'REG_SZ', value: 'Regedit do Flash' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'ActiveDeveloped', type: 'REG_SZ', value: 'Regedit do Flash' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'ActiveFix', type: 'REG_SZ', value: '1.0' },
      { path: 'HKU\\.DEFAULT\\Control Panel\\Mouse', name: 'Beep', type: 'REG_SZ', value: 'No' },
      { path: 'HKU\\.DEFAULT\\Control Panel\\Mouse', name: 'ExtendedSounds', type: 'REG_SZ', value: 'No' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'ActiveWindowTracking', type: 'REG_DWORD', value: 0 },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'Beep', type: 'REG_SZ', value: 'No' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'DoubleClickHeight', type: 'REG_SZ', value: '4' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'DoubleClickSpeed', type: 'REG_SZ', value: '500' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'DoubleClickWidth', type: 'REG_SZ', value: '4' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'ExtendedSounds', type: 'REG_SZ', value: 'No' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'MouseHoverHeight', type: 'REG_SZ', value: '4' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'MouseHoverWidth', type: 'REG_SZ', value: '4' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'MouseHoverTime', type: 'REG_SZ', value: '8' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'MouseSensitivity', type: 'REG_SZ', value: '10' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'MouseSpeed', type: 'REG_SZ', value: '0' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'MouseThreshold1', type: 'REG_SZ', value: '0' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'MouseThreshold2', type: 'REG_SZ', value: '0' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'MouseTrails', type: 'REG_SZ', value: '0' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'SmoothMouseXCurve', type: 'REG_BINARY', value: '0000000000000000c0cc0c0000000000809919000000000040662600000000000033330000000000' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'SmoothMouseYCurve', type: 'REG_BINARY', value: '0000000000000000000038000000000000007000000000000000a800000000000000e00000000000' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'SnapToDefaultButton', type: 'REG_SZ', value: '0' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'SwapMouseButtons', type: 'REG_SZ', value: '0' }
    ]
  },
  'loord-v0': {
    name: 'LOORD REGEDIT V0',
    fix: '0.0',
    keys: [
      { path: 'HKCU\\Control Panel\\Mouse', name: 'ActiveDeveloped', type: 'REG_SZ', value: 'LOORD REGEDIT' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'ActiveFix', type: 'REG_SZ', value: '18.0' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'ActiveWindowTracking', type: 'REG_DWORD', value: 1 },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'Beep', type: 'REG_SZ', value: 'No' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'Beep2', type: 'REG_SZ', value: 'No' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'DefaultTTL', type: 'REG_DWORD', value: 32767 },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'DoubleClickHeight', type: 'REG_SZ', value: '2' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'DoubleClickSpeed', type: 'REG_SZ', value: '500' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'DoubleClickSpeed2', type: 'REG_SZ', value: '0,47' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'DoubleClickWidth', type: 'REG_SZ', value: '6' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'DoubleClickWidth2', type: 'REG_SZ', value: '0,5' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'EnablePMTUBHDetect', type: 'REG_DWORD', value: 256 },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'EnablePMTUDiscovery', type: 'REG_DWORD', value: 17 },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'ExtendedSounds', type: 'REG_SZ', value: 'No' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'Fov', type: 'REG_SZ', value: '20000' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'MouseCl', type: 'REG_SZ', value: '55' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'Mousecontroslub', type: 'REG_SZ', value: '1' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'MouseCP', type: 'REG_SZ', value: '55' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'Mousecrib', type: 'REG_SZ', value: '10' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'MouseGrab', type: 'REG_SZ', value: '908' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'MouseHoverHeight', type: 'REG_SZ', value: '6' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'MouseHoverWidth', type: 'REG_SZ', value: '4' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'MouseSensitivity', type: 'REG_SZ', value: '10' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'MouseSpeed', type: 'REG_SZ', value: '0' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'MouseSpeed2', type: 'REG_SZ', value: '1' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'MouseStickOn', type: 'REG_SZ', value: '10' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'MouseThreshold1', type: 'REG_SZ', value: '0' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'MouseThreshold2', type: 'REG_SZ', value: '0' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'MouseTK', type: 'REG_SZ', value: '810' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'Mousetrack', type: 'REG_SZ', value: '908' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'MouseTrails', type: 'REG_SZ', value: '0' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'SackOpts', type: 'REG_DWORD', value: 1 },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'SmoothMouseXCurve', type: 'REG_BINARY', value: '68ef4fd4f077699036373536353936390000000000000000000000000000000000000000' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'SmoothMouseYCurve', type: 'REG_BINARY', value: '696f76333533653664733536396475633330000000000000000000000000000000000000' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'SnapToDefaultButton', type: 'REG_SZ', value: '0' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'SwapMouseButtons', type: 'REG_SZ', value: '0' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'Tcp1323Opts', type: 'REG_DWORD', value: 4 },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'TCPDelAckTicks', type: 'REG_DWORD', value: 4 },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'TcpMaxDataRetransmissions', type: 'REG_DWORD', value: 3 },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'TcpWindowSize', type: 'REG_DWORD', value: 372300 },
      ...commonLatencyKeys
    ]
  },
  'lord-v1': {
    name: 'LORD REGEDIT V1',
    fix: '1.0',
    keys: [
      { path: 'HKCU\\Control Panel\\Mouse', name: 'ActiveDeveloped', type: 'REG_SZ', value: 'LORD' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'ActiveFix', type: 'REG_SZ', value: '18.0' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'ActiveWindowTracking', type: 'REG_DWORD', value: 1 },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'Beep', type: 'REG_SZ', value: 'No' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'Beep2', type: 'REG_SZ', value: 'No' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'DefaultTTL', type: 'REG_DWORD', value: 32767 },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'DoubleClickHeight', type: 'REG_SZ', value: '2' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'DoubleClickSpeed', type: 'REG_SZ', value: '500' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'DoubleClickSpeed2', type: 'REG_SZ', value: '0,47' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'DoubleClickWidth', type: 'REG_SZ', value: '6' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'DoubleClickWidth2', type: 'REG_SZ', value: '0,5' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'EnablePMTUBHDetect', type: 'REG_DWORD', value: 256 },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'EnablePMTUDiscovery', type: 'REG_DWORD', value: 17 },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'ExtendedSounds', type: 'REG_SZ', value: 'No' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'Fov', type: 'REG_SZ', value: '20000' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'MouseCl', type: 'REG_SZ', value: '55' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'Mousecontroslub', type: 'REG_SZ', value: '1' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'MouseCP', type: 'REG_SZ', value: '55' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'Mousecrib', type: 'REG_SZ', value: '10' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'MouseGrab', type: 'REG_SZ', value: '908' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'MouseHoverHeight', type: 'REG_SZ', value: '6' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'MouseHoverWidth', type: 'REG_SZ', value: '4' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'MouseSensitivity', type: 'REG_SZ', value: '10' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'MouseSpeed', type: 'REG_SZ', value: '0' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'MouseSpeed2', type: 'REG_SZ', value: '1' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'MouseStickOn', type: 'REG_SZ', value: '10' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'MouseThreshold1', type: 'REG_SZ', value: '0' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'MouseThreshold2', type: 'REG_SZ', value: '0' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'MouseTK', type: 'REG_SZ', value: '810' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'Mousetrack', type: 'REG_SZ', value: '908' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'MouseTrails', type: 'REG_SZ', value: '0' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'SackOpts', type: 'REG_DWORD', value: 1 },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'SmoothMouseXCurve', type: 'REG_BINARY', value: '68ef4fd4f077699036373536353936390000000000000000000000000000000000000000' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'SmoothMouseYCurve', type: 'REG_BINARY', value: '696f76333533653664733536396475633330000000000000000000000000000000000000' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'SnapToDefaultButton', type: 'REG_SZ', value: '0' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'SwapMouseButtons', type: 'REG_SZ', value: '0' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'Tcp1323Opts', type: 'REG_DWORD', value: 4 },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'TCPDelAckTicks', type: 'REG_DWORD', value: 4 },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'TcpMaxDataRetransmissions', type: 'REG_DWORD', value: 3 },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'TcpWindowSize', type: 'REG_DWORD', value: 372300 },
      ...commonLatencyKeys
    ]
  },
  'lorde-v2': {
    name: 'WILL REGEDIT',
    fix: '18.0',
    keys: [
      { path: 'HKCU\\Control Panel\\Mouse', name: 'ActiveDeveloped', type: 'REG_SZ', value: 'WILL REGEDIT' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'ActiveFix', type: 'REG_SZ', value: '18.0' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'ActiveWindowTracking', type: 'REG_DWORD', value: 1 },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'Beep', type: 'REG_SZ', value: 'No' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'Beep2', type: 'REG_SZ', value: 'No' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'DefaultTTL', type: 'REG_DWORD', value: 32767 },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'DoubleClickHeight', type: 'REG_SZ', value: '2' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'DoubleClickSpeed', type: 'REG_SZ', value: '500' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'DoubleClickSpeed2', type: 'REG_SZ', value: '0,47' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'DoubleClickWidth', type: 'REG_SZ', value: '6' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'DoubleClickWidth2', type: 'REG_SZ', value: '0,5' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'EnablePMTUBHDetect', type: 'REG_DWORD', value: 256 },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'EnablePMTUDiscovery', type: 'REG_DWORD', value: 17 },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'ExtendedSounds', type: 'REG_SZ', value: 'No' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'Fov', type: 'REG_SZ', value: '20000' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'MouseCl', type: 'REG_SZ', value: '55' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'Mousecontroslub', type: 'REG_SZ', value: '1' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'MouseCP', type: 'REG_SZ', value: '55' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'Mousecrib', type: 'REG_SZ', value: '10' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'MouseGrab', type: 'REG_SZ', value: '908' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'MouseHoverHeight', type: 'REG_SZ', value: '6' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'MouseHoverWidth', type: 'REG_SZ', value: '4' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'MouseSensitivity', type: 'REG_SZ', value: '10' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'MouseSpeed', type: 'REG_SZ', value: '0' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'MouseSpeed2', type: 'REG_SZ', value: '1' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'MouseStickOn', type: 'REG_SZ', value: '10' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'MouseThreshold1', type: 'REG_SZ', value: '0' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'MouseThreshold2', type: 'REG_SZ', value: '0' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'MouseTK', type: 'REG_SZ', value: '810' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'Mousetrack', type: 'REG_SZ', value: '908' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'MouseTrails', type: 'REG_SZ', value: '0' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'SackOpts', type: 'REG_DWORD', value: 1 },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'SmoothMouseXCurve', type: 'REG_BINARY', value: '68ef4fd4f077699036373536353936390000000000000000000000000000000000000000' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'SmoothMouseYCurve', type: 'REG_BINARY', value: '696f76333533653664733536396475633330000000000000000000000000000000000000' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'SnapToDefaultButton', type: 'REG_SZ', value: '0' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'SwapMouseButtons', type: 'REG_SZ', value: '0' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'Tcp1323Opts', type: 'REG_DWORD', value: 4 },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'TCPDelAckTicks', type: 'REG_DWORD', value: 4 },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'TcpMaxDataRetransmissions', type: 'REG_DWORD', value: 3 },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'TcpWindowSize', type: 'REG_DWORD', value: 372300 },
      ...commonLatencyKeys
    ]
  },
  'loord-v3': {
    name: 'LOORD REGEDIT V3',
    fix: '3.0',
    keys: [
      { path: 'HKCU\\Control Panel\\Mouse', name: 'ActiveDeveloped', type: 'REG_SZ', value: 'LOORD REGEDIT V3' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'ActiveFix', type: 'REG_SZ', value: '3.0' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'ActiveWindowTracking', type: 'REG_DWORD', value: 1 },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'Beep', type: 'REG_SZ', value: 'No' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'Beep2', type: 'REG_SZ', value: 'No' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'DefaultTTL', type: 'REG_DWORD', value: 32767 },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'DoubleClickHeight', type: 'REG_SZ', value: '2' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'DoubleClickSpeed', type: 'REG_SZ', value: '500' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'DoubleClickSpeed2', type: 'REG_SZ', value: '0,47' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'DoubleClickWidth', type: 'REG_SZ', value: '6' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'DoubleClickWidth2', type: 'REG_SZ', value: '0,5' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'EnablePMTUBHDetect', type: 'REG_DWORD', value: 256 },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'EnablePMTUDiscovery', type: 'REG_DWORD', value: 17 },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'ExtendedSounds', type: 'REG_SZ', value: 'No' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'Fov', type: 'REG_SZ', value: '20000' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'MouseCl', type: 'REG_SZ', value: '55' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'Mousecontroslub', type: 'REG_SZ', value: '1' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'MouseCP', type: 'REG_SZ', value: '55' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'Mousecrib', type: 'REG_SZ', value: '10' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'MouseGrab', type: 'REG_SZ', value: '908' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'MouseHoverHeight', type: 'REG_SZ', value: '6' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'MouseHoverWidth', type: 'REG_SZ', value: '4' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'MouseSensitivity', type: 'REG_SZ', value: '10' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'MouseSpeed', type: 'REG_SZ', value: '0' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'MouseSpeed2', type: 'REG_SZ', value: '1' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'MouseStickOn', type: 'REG_SZ', value: '10' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'MouseThreshold1', type: 'REG_SZ', value: '0' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'MouseThreshold2', type: 'REG_SZ', value: '0' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'MouseTK', type: 'REG_SZ', value: '810' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'Mousetrack', type: 'REG_SZ', value: '908' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'MouseTrails', type: 'REG_SZ', value: '0' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'SackOpts', type: 'REG_DWORD', value: 1 },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'SmoothMouseXCurve', type: 'REG_BINARY', value: '68ef4fd4f077699036373536353936390000000000000000000000000000000000000000' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'SmoothMouseYCurve', type: 'REG_BINARY', value: '696f76333533653664733536396475633330000000000000000000000000000000000000' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'SnapToDefaultButton', type: 'REG_SZ', value: '0' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'SwapMouseButtons', type: 'REG_SZ', value: '0' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'Tcp1323Opts', type: 'REG_DWORD', value: 4 },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'TCPDelAckTicks', type: 'REG_DWORD', value: 4 },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'TcpMaxDataRetransmissions', type: 'REG_DWORD', value: 3 },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'TcpWindowSize', type: 'REG_DWORD', value: 372300 },
      ...commonLatencyKeys
    ]
  },
  'mouse-sem-aceleracao': {
    name: 'MOUSE SEM ACELERACAO 1:1',
    fix: '1.0',
    keys: [
      { path: 'HKCU\\Control Panel\\Mouse', name: 'MouseSpeed', type: 'REG_SZ', value: '0' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'MouseThreshold1', type: 'REG_SZ', value: '0' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'MouseThreshold2', type: 'REG_SZ', value: '0' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'SmoothMouseXCurve', type: 'REG_BINARY', value: '0000000000000000c0cc0c0000000000809919000000000040662600000000000033330000000000' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'SmoothMouseYCurve', type: 'REG_BINARY', value: '0000000000000000000038000000000000007000000000000000a800000000000000e00000000000' },
      ...commonLatencyKeys
    ]
  },
  'mira-clean-pesadinho': {
    name: 'MIRA CLEAN / PESADINHO 1:1',
    fix: '4.0',
    keys: [
      { path: 'HKCU\\Control Panel\\Mouse', name: 'ActiveWindowTracking', type: 'REG_DWORD', value: 0 },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'Beep', type: 'REG_SZ', value: 'No' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'DoubleClickHeight', type: 'REG_SZ', value: '4' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'DoubleClickSpeed', type: 'REG_SZ', value: '500' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'DoubleClickWidth', type: 'REG_SZ', value: '4' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'ExtendedSounds', type: 'REG_SZ', value: 'No' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'MouseHoverHeight', type: 'REG_SZ', value: '4' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'MouseHoverWidth', type: 'REG_SZ', value: '4' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'MouseSensitivity', type: 'REG_SZ', value: '10' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'MouseSpeed', type: 'REG_SZ', value: '0' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'MouseThreshold1', type: 'REG_SZ', value: '0' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'MouseThreshold2', type: 'REG_SZ', value: '0' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'MouseTrails', type: 'REG_SZ', value: '0' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'SnapToDefaultButton', type: 'REG_SZ', value: '0' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'SwapMouseButtons', type: 'REG_SZ', value: '0' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'SmoothMouseXCurve', type: 'REG_BINARY', value: '0000000000000000c0cc0c0000000000809919000000000040662600000000000033330000000000' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'SmoothMouseYCurve', type: 'REG_BINARY', value: '0000000000000000000038000000000000007000000000000000a800000000000000e00000000000' },
      { path: 'HKU\\.DEFAULT\\Control Panel\\Mouse', name: 'Beep', type: 'REG_SZ', value: 'No' },
      { path: 'HKU\\.DEFAULT\\Control Panel\\Mouse', name: 'ExtendedSounds', type: 'REG_SZ', value: 'No' },
      { path: 'HKU\\.DEFAULT\\Control Panel\\Mouse', name: 'MouseSpeed', type: 'REG_SZ', value: '0' },
      { path: 'HKU\\.DEFAULT\\Control Panel\\Mouse', name: 'MouseThreshold1', type: 'REG_SZ', value: '0' },
      { path: 'HKU\\.DEFAULT\\Control Panel\\Mouse', name: 'MouseThreshold2', type: 'REG_SZ', value: '0' },
      ...commonLatencyKeys
    ]
  },
  'kant-v1': {
    name: 'KANT REGEDIT V1',
    fix: '1.0',
    keys: [
      { path: 'HKCU\\Control Panel\\Mouse', name: 'ActiveWindowTracking', type: 'REG_DWORD', value: 0 },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'Beep', type: 'REG_SZ', value: 'No' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'DoubleClickHeight', type: 'REG_SZ', value: '4' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'DoubleClickSpeed', type: 'REG_SZ', value: '480' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'DoubleClickWidth', type: 'REG_SZ', value: '4' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'ExtendedSounds', type: 'REG_SZ', value: 'No' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'MouseHoverHeight', type: 'REG_SZ', value: '4' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'MouseHoverWidth', type: 'REG_SZ', value: '4' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'MouseSensitivity', type: 'REG_SZ', value: '10' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'MouseSpeed', type: 'REG_SZ', value: '0' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'MouseThreshold1', type: 'REG_SZ', value: '0' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'MouseThreshold2', type: 'REG_SZ', value: '0' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'MouseTrails', type: 'REG_SZ', value: '0' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'SmoothMouseXCurve', type: 'REG_BINARY', value: '0000000000000000156e000000000000004001000000000029dc0300000000000000280000000000' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'SmoothMouseYCurve', type: 'REG_BINARY', value: '0000000000000000fd11010000000000002404000000000000fc12000000000000c0bb0100000000' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'SnapToDefaultButton', type: 'REG_SZ', value: '0' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'SwapMouseButtons', type: 'REG_SZ', value: '0' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'Active', type: 'REG_SZ', value: 'Regedit V1' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'ActiveAC', type: 'REG_SZ', value: 'Regedit V1' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'ActiveDevoloped', type: 'REG_SZ', value: 'Ted Exe#0001' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'ActiveFix', type: 'REG_SZ', value: 'Regedit V1' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'ActiveUser', type: 'REG_SZ', value: 'tedexe' },
      ...commonLatencyKeys
    ]
  },
  'vip-lock-sense': {
    name: 'VIP LOCK SENSE 1:1 (Anti-Tremer & Head Lock Supremo)',
    fix: '9.0',
    keys: [
      { path: 'HKCU\\Control Panel\\Mouse', name: 'ActiveWindowTracking', type: 'REG_DWORD', value: 0 },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'Beep', type: 'REG_SZ', value: 'No' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'DoubleClickHeight', type: 'REG_SZ', value: '4' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'DoubleClickSpeed', type: 'REG_SZ', value: '480' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'DoubleClickWidth', type: 'REG_SZ', value: '4' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'DoubleClickHeight2', type: 'REG_SZ', value: '0,7' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'DoubleClickSpeed2', type: 'REG_SZ', value: '0,47' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'DoubleClickWidth2', type: 'REG_SZ', value: '0,5' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'ExtendedSounds', type: 'REG_SZ', value: 'No' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'MouseHoverHeight', type: 'REG_SZ', value: '4' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'MouseHoverTime', type: 'REG_SZ', value: '4' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'MouseHoverWidth', type: 'REG_SZ', value: '4' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'MouseSensitivity', type: 'REG_SZ', value: '10' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'MouseSpeed', type: 'REG_SZ', value: '0' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'MouseThreshold1', type: 'REG_SZ', value: '0' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'MouseThreshold2', type: 'REG_SZ', value: '0' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'MouseTrails', type: 'REG_SZ', value: '0' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'MouseGrab', type: 'REG_SZ', value: '908' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'MouseStickOn', type: 'REG_SZ', value: '10' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'Fov', type: 'REG_SZ', value: '20000' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'MouseTK', type: 'REG_SZ', value: '810' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'Mousetrack', type: 'REG_SZ', value: '908' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'Mousecontrolusb', type: 'REG_SZ', value: '1' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'MouseCP', type: 'REG_SZ', value: '55' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'MouseCL', type: 'REG_SZ', value: '55' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'SmoothMouseXCurve', type: 'REG_BINARY', value: '0000000000000000c0cc0c0000000000809919000000000040662600000000000033330000000000' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'SmoothMouseYCurve', type: 'REG_BINARY', value: '0000000000000000000038000000000000007000000000000000a800000000000000e00000000000' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'SnapToDefaultButton', type: 'REG_SZ', value: '0' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'SwapMouseButtons', type: 'REG_SZ', value: '0' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'Active', type: 'REG_SZ', value: 'VIP Lock Sense V9' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'ActiveAC', type: 'REG_SZ', value: 'VIP Lock Sense' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'ActiveDeveloped', type: 'REG_SZ', value: 'VIP LOCK SENSE 1:1' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'ActiveFix', type: 'REG_SZ', value: '9.0' },
      { path: 'HKCU\\Control Panel\\Desktop', name: 'MenuShowDelay', type: 'REG_SZ', value: '0' },
      { path: 'HKCU\\Control Panel\\Desktop', name: 'ForegroundLockTimeout', type: 'REG_DWORD', value: 0 },
      { path: 'HKCU\\Control Panel\\Desktop', name: 'ForegroundFlashCount', type: 'REG_DWORD', value: 0 },
      { path: 'HKCU\\System\\GameConfigStore', name: 'GameDVR_Enabled', type: 'REG_DWORD', value: 0 },
      { path: 'HKCU\\System\\GameConfigStore', name: 'GameDVR_FSEBehaviorMode', type: 'REG_DWORD', value: 2 },
      { path: 'HKCU\\System\\GameConfigStore', name: 'GameDVR_HonorUserFSEBehaviorMode', type: 'REG_DWORD', value: 1 },
      { path: 'HKCU\\System\\GameConfigStore', name: 'GameDVR_DXGIHonorFSEWindowsCompatible', type: 'REG_DWORD', value: 1 },
      { path: 'HKCU\\System\\GameConfigStore', name: 'GameDVR_EFSEFeatureFlags', type: 'REG_DWORD', value: 0 },
      { path: 'HKCU\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\GameDVR', name: 'AppCaptureEnabled', type: 'REG_DWORD', value: 0 },
      { path: 'HKCU\\Software\\Microsoft\\GameBar', name: 'AutoGameModeEnabled', type: 'REG_DWORD', value: 1 },
      { path: 'HKCU\\Software\\Microsoft\\GameBar', name: 'AllowAutoGameMode', type: 'REG_DWORD', value: 1 },
      { path: 'HKCU\\Software\\Microsoft\\GameBar', name: 'UseNexusForGameBarEnabled', type: 'REG_DWORD', value: 0 },
      { path: 'HKLM\\SYSTEM\\CurrentControlSet\\Services\\USB', name: 'DisableSelectiveSuspend', type: 'REG_DWORD', value: 1 },
      { path: 'HKLM\\SYSTEM\\CurrentControlSet\\Services\\mouclass\\Parameters', name: 'MouseDataQueueSize', type: 'REG_DWORD', value: 100 },
      { path: 'HKLM\\SYSTEM\\CurrentControlSet\\Services\\kbdclass\\Parameters', name: 'KeyboardDataQueueSize', type: 'REG_DWORD', value: 100 },
      { path: 'HKLM\\SYSTEM\\CurrentControlSet\\Control\\PriorityControl', name: 'IRQ8Priority', type: 'REG_DWORD', value: 1 },
      { path: 'HKLM\\SYSTEM\\CurrentControlSet\\Control\\PriorityControl', name: 'Win32PrioritySeparation', type: 'REG_DWORD', value: 38 },
      { path: 'HKLM\\SYSTEM\\CurrentControlSet\\Control\\Session Manager\\Kernel', name: 'GlobalTimerResolutionRequests', type: 'REG_DWORD', value: 1 },
      { path: 'HKLM\\SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Multimedia\\SystemProfile', name: 'SystemResponsiveness', type: 'REG_DWORD', value: 0 },
      { path: 'HKLM\\SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Multimedia\\SystemProfile', name: 'NetworkThrottlingIndex', type: 'REG_DWORD', value: 4294967295 },
      { path: 'HKLM\\SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Multimedia\\SystemProfile\\Tasks\\Games', name: 'GPU Priority', type: 'REG_DWORD', value: 8 },
      { path: 'HKLM\\SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Multimedia\\SystemProfile\\Tasks\\Games', name: 'Priority', type: 'REG_DWORD', value: 6 },
      { path: 'HKLM\\SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Multimedia\\SystemProfile\\Tasks\\Games', name: 'Scheduling Category', type: 'REG_SZ', value: 'High' },
      { path: 'HKLM\\SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Multimedia\\SystemProfile\\Tasks\\Games', name: 'SFIO Priority', type: 'REG_SZ', value: 'High' },
      { path: 'HKU\\.DEFAULT\\Control Panel\\Mouse', name: 'Beep', type: 'REG_SZ', value: 'No' },
      { path: 'HKU\\.DEFAULT\\Control Panel\\Mouse', name: 'ExtendedSounds', type: 'REG_SZ', value: 'No' },
      { path: 'HKU\\.DEFAULT\\Control Panel\\Mouse', name: 'MouseSpeed', type: 'REG_SZ', value: '0' },
      { path: 'HKU\\.DEFAULT\\Control Panel\\Mouse', name: 'MouseThreshold1', type: 'REG_SZ', value: '0' },
      { path: 'HKU\\.DEFAULT\\Control Panel\\Mouse', name: 'MouseThreshold2', type: 'REG_SZ', value: '0' },
      ...commonLatencyKeys
    ]
  },
  'loord-3-sense-full-red': {
    name: 'LOORD 3.0 SENSE FULL RED (Ultra Sense + BCD + USB Boost)',
    fix: '3.0',
    keys: [
      { path: 'HKCU\\Control Panel\\Mouse', name: 'ActiveWindowTracking', type: 'REG_DWORD', value: 0 },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'Beep', type: 'REG_SZ', value: 'No' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'DoubleClickHeight', type: 'REG_SZ', value: '4' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'DoubleClickSpeed', type: 'REG_SZ', value: '500' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'DoubleClickWidth', type: 'REG_SZ', value: '4' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'ExtendedSounds', type: 'REG_SZ', value: 'No' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'MouseHoverHeight', type: 'REG_SZ', value: '0' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'MouseHoverTime', type: 'REG_SZ', value: '10' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'MouseHoverWidth', type: 'REG_SZ', value: '0' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'MouseSensitivity', type: 'REG_SZ', value: '10' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'MouseSpeed', type: 'REG_SZ', value: '0' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'MouseThreshold1', type: 'REG_SZ', value: '0' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'MouseThreshold2', type: 'REG_SZ', value: '0' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'MouseTrails', type: 'REG_SZ', value: '0' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'ClickLock', type: 'REG_SZ', value: '0' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'ClickLockTime', type: 'REG_SZ', value: '1200' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'SnapToDefaultButton', type: 'REG_SZ', value: '0' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'SwapMouseButtons', type: 'REG_SZ', value: '0' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'SmoothMouseXCurve', type: 'REG_BINARY', value: '0000000000000000156e000000000000004001000000000029dc0300000000000000280000000000ffff0f0000000000' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'SmoothMouseYCurve', type: 'REG_BINARY', value: '0000000000000000fd11010000000000002404000000000000fc12000000000000c0bb0100000000000058020000000000' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'Active', type: 'REG_SZ', value: 'LOORD 3.0 SENSE FULL RED' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'ActiveDeveloped', type: 'REG_SZ', value: 'LOORD 3.0 SENSE FULL RED' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'ActiveFix', type: 'REG_SZ', value: '3.0' },
      { path: 'HKCU\\Control Panel\\Keyboard', name: 'KeyboardDelay', type: 'REG_SZ', value: '0' },
      { path: 'HKCU\\Control Panel\\Keyboard', name: 'KeyboardSpeed', type: 'REG_SZ', value: '31' },
      { path: 'HKCU\\Control Panel\\Accessibility\\Keyboard Response', name: 'AutoRepeatDelay', type: 'REG_SZ', value: '0' },
      { path: 'HKCU\\Control Panel\\Accessibility\\Keyboard Response', name: 'AutoRepeatRate', type: 'REG_SZ', value: '0' },
      { path: 'HKCU\\Control Panel\\Accessibility\\Keyboard Response', name: 'DelayBeforeAcceptance', type: 'REG_SZ', value: '0' },
      { path: 'HKCU\\Control Panel\\Accessibility\\Keyboard Response', name: 'Flags', type: 'REG_SZ', value: '0' },
      { path: 'HKCU\\Control Panel\\Accessibility\\StickyKeys', name: 'Flags', type: 'REG_SZ', value: '0' },
      { path: 'HKCU\\Control Panel\\Accessibility\\ToggleKeys', name: 'Flags', type: 'REG_SZ', value: '0' },
      { path: 'HKCU\\Control Panel\\Accessibility\\MouseKeys', name: 'Flags', type: 'REG_SZ', value: '0' },
      { path: 'HKLM\\SYSTEM\\CurrentControlSet\\Services\\mouclass\\Parameters', name: 'MouseDataQueueSize', type: 'REG_DWORD', value: 100 },
      { path: 'HKLM\\SYSTEM\\CurrentControlSet\\Services\\mouhid\\Parameters', name: 'MouseDataQueueSize', type: 'REG_DWORD', value: 100 },
      { path: 'HKLM\\SYSTEM\\CurrentControlSet\\Services\\kbdclass\\Parameters', name: 'KeyboardDataQueueSize', type: 'REG_DWORD', value: 100 },
      { path: 'HKLM\\SYSTEM\\CurrentControlSet\\Services\\USB', name: 'DisableSelectiveSuspend', type: 'REG_DWORD', value: 1 },
      { path: 'HKLM\\SYSTEM\\CurrentControlSet\\Services\\HidUsb\\Parameters', name: 'IdleEnabled', type: 'REG_DWORD', value: 0 },
      { path: 'HKLM\\SYSTEM\\CurrentControlSet\\Services\\USBXHCI\\Parameters', name: 'EnableSelectiveSuspend', type: 'REG_DWORD', value: 0 },
      { path: 'HKLM\\SYSTEM\\CurrentControlSet\\Services\\USBXHCI\\Parameters', name: 'DisableSelectiveSuspend', type: 'REG_DWORD', value: 1 },
      { path: 'HKLM\\SYSTEM\\CurrentControlSet\\Enum\\USB', name: 'SelectiveSuspendEnabled', type: 'REG_DWORD', value: 0 },
      { path: 'HKCU\\Control Panel\\Desktop', name: 'MenuShowDelay', type: 'REG_SZ', value: '0' },
      { path: 'HKCU\\Control Panel\\Desktop', name: 'ForegroundLockTimeout', type: 'REG_DWORD', value: 0 },
      { path: 'HKCU\\Control Panel\\Desktop', name: 'ForegroundFlashCount', type: 'REG_DWORD', value: 0 },
      { path: 'HKCU\\System\\GameConfigStore', name: 'GameDVR_Enabled', type: 'REG_DWORD', value: 0 },
      { path: 'HKCU\\System\\GameConfigStore', name: 'GameDVR_FSEBehaviorMode', type: 'REG_DWORD', value: 2 },
      { path: 'HKCU\\System\\GameConfigStore', name: 'GameDVR_HonorUserFSEBehaviorMode', type: 'REG_DWORD', value: 1 },
      { path: 'HKCU\\System\\GameConfigStore', name: 'GameDVR_DXGIHonorFSEWindowsCompatible', type: 'REG_DWORD', value: 1 },
      { path: 'HKCU\\System\\GameConfigStore', name: 'GameDVR_EFSEFeatureFlags', type: 'REG_DWORD', value: 0 },
      { path: 'HKCU\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\GameDVR', name: 'AppCaptureEnabled', type: 'REG_DWORD', value: 0 },
      { path: 'HKCU\\Software\\Microsoft\\GameBar', name: 'AutoGameModeEnabled', type: 'REG_DWORD', value: 1 },
      { path: 'HKCU\\Software\\Microsoft\\GameBar', name: 'AllowAutoGameMode', type: 'REG_DWORD', value: 1 },
      { path: 'HKCU\\Software\\Microsoft\\GameBar', name: 'UseNexusForGameBarEnabled', type: 'REG_DWORD', value: 0 },
      { path: 'HKLM\\SYSTEM\\CurrentControlSet\\Control\\PriorityControl', name: 'IRQ8Priority', type: 'REG_DWORD', value: 1 },
      { path: 'HKLM\\SYSTEM\\CurrentControlSet\\Control\\PriorityControl', name: 'Win32PrioritySeparation', type: 'REG_DWORD', value: 38 },
      { path: 'HKLM\\SYSTEM\\CurrentControlSet\\Control\\Session Manager\\Kernel', name: 'GlobalTimerResolutionRequests', type: 'REG_DWORD', value: 1 },
      { path: 'HKLM\\SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Multimedia\\SystemProfile', name: 'SystemResponsiveness', type: 'REG_DWORD', value: 0 },
      { path: 'HKLM\\SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Multimedia\\SystemProfile', name: 'NetworkThrottlingIndex', type: 'REG_DWORD', value: 4294967295 },
      { path: 'HKLM\\SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Multimedia\\SystemProfile\\Tasks\\Games', name: 'GPU Priority', type: 'REG_DWORD', value: 8 },
      { path: 'HKLM\\SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Multimedia\\SystemProfile\\Tasks\\Games', name: 'Priority', type: 'REG_DWORD', value: 6 },
      { path: 'HKLM\\SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Multimedia\\SystemProfile\\Tasks\\Games', name: 'Scheduling Category', type: 'REG_SZ', value: 'High' },
      { path: 'HKLM\\SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Multimedia\\SystemProfile\\Tasks\\Games', name: 'SFIO Priority', type: 'REG_SZ', value: 'High' },
      { path: 'HKU\\.DEFAULT\\Control Panel\\Mouse', name: 'Beep', type: 'REG_SZ', value: 'No' },
      { path: 'HKU\\.DEFAULT\\Control Panel\\Mouse', name: 'ExtendedSounds', type: 'REG_SZ', value: 'No' },
      { path: 'HKU\\.DEFAULT\\Control Panel\\Mouse', name: 'MouseSpeed', type: 'REG_SZ', value: '0' },
      { path: 'HKU\\.DEFAULT\\Control Panel\\Mouse', name: 'MouseThreshold1', type: 'REG_SZ', value: '0' },
      { path: 'HKU\\.DEFAULT\\Control Panel\\Mouse', name: 'MouseThreshold2', type: 'REG_SZ', value: '0' },
      ...commonLatencyKeys
    ]
  },
  'full-red-ump': {
    name: 'REGEDIT FULL RED UMP (Precisão & Disparo Rápido)',
    fix: '1.0',
    keys: [
      { path: 'HKCU\\Control Panel\\Mouse', name: 'ActiveWindowTracking', type: 'REG_DWORD', value: 0 },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'Beep', type: 'REG_SZ', value: 'No' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'DoubleClickHeight', type: 'REG_SZ', value: '4' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'DoubleClickSpeed', type: 'REG_SZ', value: '500' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'DoubleClickWidth', type: 'REG_SZ', value: '4' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'ExtendedSounds', type: 'REG_SZ', value: 'No' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'MouseHoverHeight', type: 'REG_SZ', value: '0' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'MouseHoverTime', type: 'REG_SZ', value: '1000' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'MouseHoverWidth', type: 'REG_SZ', value: '0' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'MouseSensitivity', type: 'REG_SZ', value: '10' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'MouseSpeed', type: 'REG_SZ', value: '0' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'MouseThreshold1', type: 'REG_SZ', value: '0' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'MouseThreshold2', type: 'REG_SZ', value: '0' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'MouseTrails', type: 'REG_SZ', value: '0' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'SmoothMouseXCurve', type: 'REG_BINARY', value: '0000000000000000156e000000000000004001000000000029dc0300000000000000280000000000' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'SmoothMouseYCurve', type: 'REG_BINARY', value: '0000000000000000fd11010000000000002404000000000000fc12000000000000c0bb0100000000' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'SnapToDefaultButton', type: 'REG_SZ', value: '0' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'SwapMouseButtons', type: 'REG_SZ', value: '0' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'Active', type: 'REG_SZ', value: 'REGEDIT FULL RED UMP' },
      { path: 'HKU\\.DEFAULT\\Control Panel\\Mouse', name: 'Beep', type: 'REG_SZ', value: 'No' },
      { path: 'HKU\\.DEFAULT\\Control Panel\\Mouse', name: 'ExtendedSounds', type: 'REG_SZ', value: 'No' },
      { path: 'HKU\\.DEFAULT\\Control Panel\\Mouse', name: 'MouseSpeed', type: 'REG_SZ', value: '0' },
      { path: 'HKU\\.DEFAULT\\Control Panel\\Mouse', name: 'MouseThreshold1', type: 'REG_SZ', value: '0' },
      { path: 'HKU\\.DEFAULT\\Control Panel\\Mouse', name: 'MouseThreshold2', type: 'REG_SZ', value: '0' },
      ...commonLatencyKeys
    ]
  },
  'ultra-emu-boost': {
    name: 'ULTRA EMULATOR BOOST 1:1 (Sensibilidade Real & Alto Desempenho)',
    fix: '1.0',
    keys: [
      { path: 'HKCU\\Control Panel\\Mouse', name: 'MouseSpeed', type: 'REG_SZ', value: '0' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'MouseThreshold1', type: 'REG_SZ', value: '0' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'MouseThreshold2', type: 'REG_SZ', value: '0' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'MouseSensitivity', type: 'REG_SZ', value: '10' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'MouseTrails', type: 'REG_SZ', value: '0' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'SnapToDefaultButton', type: 'REG_SZ', value: '0' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'Active', type: 'REG_SZ', value: 'ULTRA EMULATOR BOOST 1:1' },
      { path: 'HKCU\\System\\GameConfigStore', name: 'GameDVR_Enabled', type: 'REG_DWORD', value: 0 },
      { path: 'HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\GameDVR', name: 'AppCaptureEnabled', type: 'REG_DWORD', value: 0 },
      { path: 'HKLM\\SOFTWARE\\Policies\\Microsoft\\Windows\\GameDVR', name: 'AllowGameDVR', type: 'REG_DWORD', value: 0 },
      { path: 'HKLM\\SYSTEM\\CurrentControlSet\\Services\\USB', name: 'DisableSelectiveSuspend', type: 'REG_DWORD', value: 1 },
      { path: 'HKLM\\SYSTEM\\CurrentControlSet\\Services\\USBXHCI\\Parameters', name: 'DisableSelectiveSuspend', type: 'REG_DWORD', value: 1 },
      ...commonLatencyKeys
    ]
  },
  'zero-curve-raw': {
    name: 'ZERO CURVE RAW INPUT 1:1 (Mira Estável & Ping Ultrabaixo)',
    fix: '1.0',
    keys: [
      { path: 'HKCU\\Control Panel\\Mouse', name: 'ActiveWindowTracking', type: 'REG_DWORD', value: 0 },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'Beep', type: 'REG_SZ', value: 'No' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'DoubleClickHeight', type: 'REG_SZ', value: '4' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'DoubleClickSpeed', type: 'REG_SZ', value: '500' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'DoubleClickWidth', type: 'REG_SZ', value: '4' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'ExtendedSounds', type: 'REG_SZ', value: 'No' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'MouseHoverHeight', type: 'REG_SZ', value: '4' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'MouseHoverTime', type: 'REG_SZ', value: '400' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'MouseHoverWidth', type: 'REG_SZ', value: '4' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'MouseSensitivity', type: 'REG_SZ', value: '6' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'MouseSpeed', type: 'REG_SZ', value: '0' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'MouseThreshold1', type: 'REG_SZ', value: '0' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'MouseThreshold2', type: 'REG_SZ', value: '0' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'MouseTrails', type: 'REG_SZ', value: '0' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'SnapToDefaultButton', type: 'REG_SZ', value: '0' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'SwapMouseButtons', type: 'REG_SZ', value: '0' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'SmoothMouseXCurve', type: 'REG_BINARY', value: '00000000000000000000000000000000000000000000000000000000000000000000000000000000' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'SmoothMouseYCurve', type: 'REG_BINARY', value: '00000000000000000000000000000000000000000000000000000000000000000000000000000000' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'Active', type: 'REG_SZ', value: 'ZERO CURVE RAW INPUT 1:1' },
      { path: 'HKLM\\SYSTEM\\CurrentControlSet\\Services\\Tcpip\\Parameters', name: 'EnablePMTUBHDetect', type: 'REG_DWORD', value: 1 },
      { path: 'HKLM\\SYSTEM\\CurrentControlSet\\Services\\Tcpip\\Parameters', name: 'EnablePMTUDiscovery', type: 'REG_DWORD', value: 1 },
      { path: 'HKLM\\SYSTEM\\CurrentControlSet\\Services\\Tcpip\\Parameters', name: 'GlobalMaxTcpWindowSize', type: 'REG_DWORD', value: 32767 },
      { path: 'HKLM\\SYSTEM\\CurrentControlSet\\Services\\Tcpip\\Parameters', name: 'Tcp1323Opts', type: 'REG_DWORD', value: 3 },
      { path: 'HKLM\\SYSTEM\\CurrentControlSet\\Services\\Tcpip\\Parameters', name: 'TcpMaxDupAcks', type: 'REG_DWORD', value: 2 },
      { path: 'HKLM\\SYSTEM\\CurrentControlSet\\Services\\Tcpip\\Parameters', name: 'SackOpts', type: 'REG_DWORD', value: 1 },
      { path: 'HKLM\\SYSTEM\\CurrentControlSet\\Services\\Tcpip\\Parameters', name: 'TcpWindowSize', type: 'REG_DWORD', value: 372300 },
      ...commonLatencyKeys
    ]
  },
  'ff-mouse-maximo': {
    name: 'FREE FIRE MOUSE NO MÁXIMO (Sensibilidade 10/11 & IRQ8 Timer Boost)',
    fix: '1.0',
    keys: [
      { path: 'HKCU\\Control Panel\\Mouse', name: 'MouseSpeed', type: 'REG_SZ', value: '0' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'MouseThreshold1', type: 'REG_SZ', value: '0' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'MouseThreshold2', type: 'REG_SZ', value: '0' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'MouseSensitivity', type: 'REG_SZ', value: '10' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'MouseHoverTime', type: 'REG_SZ', value: '10' },
      { path: 'HKCU\\Control Panel\\Desktop', name: 'MenuShowDelay', type: 'REG_SZ', value: '0' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'Active', type: 'REG_SZ', value: 'FREE FIRE MOUSE NO MAXIMO' },
      { path: 'HKCU\\System\\GameConfigStore', name: 'GameDVR_Enabled', type: 'REG_DWORD', value: 0 },
      { path: 'HKCU\\System\\GameConfigStore', name: 'GameDVR_FSEBehaviorMode', type: 'REG_DWORD', value: 2 },
      { path: 'HKCU\\System\\GameConfigStore', name: 'GameDVR_HonorUserFSEBehaviorMode', type: 'REG_DWORD', value: 1 },
      { path: 'HKCU\\System\\GameConfigStore', name: 'GameDVR_DXGIHonorFSEWindowsCompatible', type: 'REG_DWORD', value: 1 },
      { path: 'HKCU\\System\\GameConfigStore', name: 'GameDVR_EFSEFeatureFlags', type: 'REG_DWORD', value: 0 },
      { path: 'HKCU\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\GameDVR', name: 'AppCaptureEnabled', type: 'REG_DWORD', value: 0 },
      { path: 'HKCU\\Software\\Microsoft\\GameBar', name: 'AutoGameModeEnabled', type: 'REG_DWORD', value: 1 },
      { path: 'HKCU\\Software\\Microsoft\\GameBar', name: 'AllowAutoGameMode', type: 'REG_DWORD', value: 1 },
      { path: 'HKCU\\Software\\Microsoft\\GameBar', name: 'UseNexusForGameBarEnabled', type: 'REG_DWORD', value: 0 },
      { path: 'HKLM\\SYSTEM\\CurrentControlSet\\Services\\USB', name: 'DisableSelectiveSuspend', type: 'REG_DWORD', value: 1 },
      { path: 'HKLM\\SYSTEM\\CurrentControlSet\\Services\\USBXHCI\\Parameters', name: 'DisableSelectiveSuspend', type: 'REG_DWORD', value: 1 },
      { path: 'HKLM\\SYSTEM\\CurrentControlSet\\Services\\mouclass\\Parameters', name: 'MouseDataQueueSize', type: 'REG_DWORD', value: 100 },
      { path: 'HKLM\\SYSTEM\\CurrentControlSet\\Control\\PriorityControl', name: 'IRQ8Priority', type: 'REG_DWORD', value: 1 },
      { path: 'HKLM\\SYSTEM\\CurrentControlSet\\Control\\PriorityControl', name: 'Win32PrioritySeparation', type: 'REG_DWORD', value: 38 },
      { path: 'HKLM\\SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Multimedia\\SystemProfile', name: 'SystemResponsiveness', type: 'REG_DWORD', value: 0 },
      { path: 'HKLM\\SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Multimedia\\SystemProfile', name: 'NetworkThrottlingIndex', type: 'REG_DWORD', value: 4294967295 },
      { path: 'HKLM\\SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Multimedia\\SystemProfile\\Tasks\\Games', name: 'GPU Priority', type: 'REG_DWORD', value: 8 },
      { path: 'HKLM\\SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Multimedia\\SystemProfile\\Tasks\\Games', name: 'Priority', type: 'REG_DWORD', value: 6 },
      { path: 'HKLM\\SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Multimedia\\SystemProfile\\Tasks\\Games', name: 'Scheduling Category', type: 'REG_SZ', value: 'High' },
      { path: 'HKLM\\SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Multimedia\\SystemProfile\\Tasks\\Games', name: 'SFIO Priority', type: 'REG_SZ', value: 'High' },
      ...commonLatencyKeys
    ]
  },
  'rikwich-pro-sense': {
    name: 'REGEDIT R!KW!CH PRO (Curva Linear 1:1 & Touch BlueStacks 750 DPI)',
    fix: '1.0',
    keys: [
      { path: 'HKCU\\Control Panel\\Mouse', name: 'ActiveWindowTracking', type: 'REG_DWORD', value: 1 },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'Beep', type: 'REG_SZ', value: 'No' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'DoubleClickHeight', type: 'REG_SZ', value: '5' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'DoubleClickHeight2', type: 'REG_SZ', value: '0,95' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'DoubleClickSpeed', type: 'REG_SZ', value: '500' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'DoubleClickWidth', type: 'REG_SZ', value: '5' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'DoubleClickWidth2', type: 'REG_SZ', value: '0,4' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'ExtendedSounds', type: 'REG_SZ', value: 'No' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'ExtendedSounds2', type: 'REG_SZ', value: 'no' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'MouseHoverHeight', type: 'REG_SZ', value: '2' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'MouseHoverTime', type: 'REG_SZ', value: '4' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'MouseHoverWidth', type: 'REG_SZ', value: '2' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'MouseSensitivity', type: 'REG_SZ', value: '10' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'MouseSpeed', type: 'REG_SZ', value: '0' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'MouseSpeed2', type: 'REG_SZ', value: '0' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'MouseThreshold1', type: 'REG_SZ', value: '0' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'MouseThreshold2', type: 'REG_SZ', value: '0' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'MouseTrails', type: 'REG_SZ', value: '0' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'SnapToDefaultButton', type: 'REG_SZ', value: '0' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'SwapMouseButtons', type: 'REG_SZ', value: '0' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'MouseThreshold12', type: 'REG_SZ', value: '0' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'MouseThreshold22', type: 'REG_SZ', value: '0' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'SmoothMouseXCurve', type: 'REG_BINARY', value: '0000000000000000c0cc2c0000000000809959000000000040668600000000000033b30000000000' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'SmoothMouseYCurve', type: 'REG_BINARY', value: '0000000000000000000038000000000000007000000000000000a800000000000000e00000000000' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'DoubleClickSpeed2', type: 'REG_SZ', value: '0,28' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'TcpWindowSize', type: 'REG_DWORD', value: 372300 },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'TcpNoDelay', type: 'REG_BINARY', value: '7f14000000000000' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'TCPDelAckTicks', type: 'REG_DWORD', value: 5 },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'Tcp1323Opts', type: 'REG_DWORD', value: 3 },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'TcpMaxDataRetransmissions', type: 'REG_DWORD', value: 3 },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'SackOpts', type: 'REG_DWORD', value: 1 },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'DefaultTTL', type: 'REG_DWORD', value: 32767 },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'Beep2', type: 'REG_SZ', value: 'No' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'EnablePMTUDiscovery', type: 'REG_DWORD', value: 1 },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'EnablePMTUBHDetect', type: 'REG_DWORD', value: 0 },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'Assist', type: 'REG_SZ', value: '𝙓 𝗥!𝗞𝗪!𝗖𝗛#0891' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'ActiveFix', type: 'REG_SZ', value: '𝙓 𝗥!𝗞𝗪!𝗖𝗛#0891' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'ActiveAC', type: 'REG_SZ', value: '𝙓 𝗥!𝗞𝗪!𝗖𝗛#0891' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'ActiveDevoloped', type: 'REG_SZ', value: '𝙓 𝗥!𝗞𝗪!𝗖𝗛#0891' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'Active', type: 'REG_SZ', value: '𝙓 𝗥!𝗞𝗪!𝗖𝗛#0891' },
      { path: 'HKLM\\SOFTWARE\\BlueStacks\\Guests\\Android\\sensibility\\0', name: 'sensibility', type: 'REG_DWORD', value: 100 },
      { path: 'HKLM\\SOFTWARE\\BlueStacks\\Guests\\Android\\sensibility\\0', name: 'SMALLESTWIDTH', type: 'REG_DWORD', value: 750 },
      { path: 'HKLM\\SOFTWARE\\BlueStacks\\Guests\\Android\\sensibility\\0', name: 'speedofmovement', type: 'REG_DWORD', value: 100 },
      { path: 'HKLM\\SOFTWARE\\BlueStacks\\Guests\\Android\\sensibility\\0', name: 'touchsensitivyty', type: 'REG_DWORD', value: 258 },
      { path: 'HKLM\\SOFTWARE\\BlueStacks\\Guests\\Android\\sensibility\\0', name: 'x', type: 'REG_DWORD', value: 1000 },
      { path: 'HKLM\\SOFTWARE\\BlueStacks\\Guests\\Android\\sensibility\\0', name: 'y', type: 'REG_DWORD', value: 2450 },
      { path: 'HKLM\\SOFTWARE\\BlueStacks\\Guests\\Android\\sensibility\\0', name: '𝙓 𝗥!𝗞𝗪!𝗖𝗛#0891 gpu', type: 'REG_DWORD', value: 100 },
      { path: 'HKLM\\SOFTWARE\\BlueStacks\\Guests\\Android\\sensibility\\0', name: '𝙓 𝗥!𝗞𝗪!𝗖𝗛#0891 cpu', type: 'REG_DWORD', value: 100 },
      { path: 'HKLM\\SOFTWARE\\BlueStacks\\Guests\\Android\\sensibility\\0', name: '𝙓 𝗥!𝗞𝗪!𝗖𝗛#0891 dpi', type: 'REG_DWORD', value: 1200 },
      { path: 'HKLM\\SOFTWARE\\BlueStacks\\Guests\\Android\\sensibility\\0', name: 'generalemulatorsensitivity', type: 'REG_DWORD', value: 100 },
      { path: 'HKLM\\SOFTWARE\\BlueStacks\\Guests\\Android\\sensibility\\0', name: 'sensitivity', type: 'REG_DWORD', value: 100 },
      { path: 'HKLM\\SOFTWARE\\BlueStacks\\Guests\\Android\\sensibility\\0', name: 'touchsensitivity', type: 'REG_DWORD', value: 256 },
      { path: 'HKLM\\SOFTWARE\\BlueStacks\\Guests\\Android\\sensibility\\0', name: '𝙓 𝗥!𝗞𝗪!𝗖𝗛#0891', type: 'REG_DWORD', value: 100 },
      { path: 'HKU\\.DEFAULT\\Control Panel\\Mouse', name: 'MouseSpeed', type: 'REG_SZ', value: '0' },
      { path: 'HKU\\.DEFAULT\\Control Panel\\Mouse', name: 'MouseThreshold1', type: 'REG_SZ', value: '0' },
      { path: 'HKU\\.DEFAULT\\Control Panel\\Mouse', name: 'MouseThreshold2', type: 'REG_SZ', value: '0' },
      ...commonLatencyKeys
    ]
  },
  'fov-lock-stick-pro': {
    name: 'REGEDIT LOCK FOV & MOUSE STICK (Trava Mira & FOV 20k)',
    fix: '1.0',
    keys: [
      { path: 'HKCU\\Control Panel\\Mouse', name: 'ActiveWindowTracking', type: 'REG_DWORD', value: 1 },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'ActiveUser', type: 'REG_SZ', value: '嬭炴㤹椰杨桧㕴㘵㜶㠷' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'Beep', type: 'REG_SZ', value: 'No' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'Assist', type: 'REG_SZ', value: '㠸〸㤹㘹㠶㠸됸孝嶴嶴嶴嶴嶴嶴嶴듧繝ⷧ孛炴嬭炴㤹椰杨桧㕴㘵㜶㠷㤷㤸〸㜹欹듧⵰㴽㵛孾㵝繝宴纴烧孾孰孛孰ⶴ둛둛둛㭬嬮뒴ⱛ됻ⱛ됮듧㯧둛宴듧㭛됮Ⱞ殴沴듳濧汯汯둩澴둬潛둬濧둬潛潬孬汯둛濧孬潯潬둬둾둾둾둾繾뒴繛듧듧宴橬㥰桪橵桨桨杨桨票杧摦睳獳睤敷睤敷獷獤獡獡慤獡晤㍳㐲㐴㔵㘵㘵㜶㜸㜶㘵㘵㘷㔵' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'ExtendedSounds', type: 'REG_SZ', value: 'no' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'MouseHoverHeight', type: 'REG_SZ', value: '100' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'MouseHoverTime', type: 'REG_SZ', value: '900' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'MouseHoverWidth', type: 'REG_SZ', value: '100' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'MouseSensitivity', type: 'REG_SZ', value: '2' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'MouseSpeed', type: 'REG_SZ', value: '4' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'MouseThreshold1', type: 'REG_SZ', value: '7' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'MouseThreshold2', type: 'REG_SZ', value: '11' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'MouseTrails', type: 'REG_SZ', value: '㠸〸㤹㘹㠶㠸됸孝嶴嶴嶴嶴嶴嶴嶴듧繝ⷧ孛炴嬭炴㤹椰杨桧㕴㘵㜶㠷㤷㤸〸㜹欹듧⵰㴽㵛孾㵝繝宴纴烧孾孰孛孰ⶴ둛둛둛㭬嬮뒴ⱛ됻ⱛ됮듧㯧둛宴듧㭛됮Ⱞ殴沴듳濧汯汯둩澴둬潛둬濧둬潛潬孬汯둛濧孬潯潬둬둾둾둾둾繾뒴繛듧듧宴橬㥰桪橵桨桨杨桨票杧摦睳獳睤敷睤敷獷獤獡獡慤獡晤㍳㐲㐴㔵㘵㘵㜶㜸㜶㘵㘵㘷㔵' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'SmoothMouseXCurve', type: 'REG_BINARY', value: '65ef4fd4dff0776990363735363539363936362d5b703435723435747279657272676c6f7eb45d3d5d2d5d5b6f69757572746572667468793775355d5b3d2d5df3b47e70e76f707ee7e7f5707ee76ce77e70b45d5b5d2d707068676674656564727777' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'SmoothMouseYCurve', type: 'REG_BINARY', value: '666f7633353365366473367964756333373363723472673566669809000000000000000000000000ddddeef4f00000033400000000000000000000000000003579376969386f70b4e7b43de7e7703d7eb4e73b3de73b7e3db4e77e3db4e77eb43d77736675647568666467667e7e5b5d5b736466676a677567667467676679377937646667663774665d5d7eb40000000000000500000000000000000f00000000000000050000000000000005f000000000000000' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'SnapToDefaultButton', type: 'REG_SZ', value: '0' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'SwapMouseButtons', type: 'REG_SZ', value: '0' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'DoubleClickSpeed2', type: 'REG_SZ', value: '0,5' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'DoubleClickWidth2', type: 'REG_SZ', value: '0,6' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'TcpWindowSize', type: 'REG_DWORD', value: 372300 },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'TcpNoDelay', type: 'REG_BINARY', value: '7f14000000000000' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'TCPDelAckTicks', type: 'REG_DWORD', value: 4 },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'Tcp1323Opts', type: 'REG_DWORD', value: 4 },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'TcpMaxDataRetransmissions', type: 'REG_DWORD', value: 3 },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'SackOpts', type: 'REG_DWORD', value: 1 },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'DefaultTTL', type: 'REG_DWORD', value: 32767 },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'Beep2', type: 'REG_SZ', value: 'No' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'EnablePMTUDiscovery', type: 'REG_DWORD', value: 17 },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'EnablePMTUBHDetect', type: 'REG_DWORD', value: 256 },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'MouseCP', type: 'REG_SZ', value: '55' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'MouseCL', type: 'REG_SZ', value: '55' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'Mousetrack', type: 'REG_SZ', value: '908' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'Mousecrib', type: 'REG_SZ', value: '10' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'Mousecontrolusb', type: 'REG_SZ', value: '1' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'MouseTK', type: 'REG_SZ', value: '810' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'Fov', type: 'REG_SZ', value: '20000' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'MouseGrab', type: 'REG_SZ', value: '908' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'MouseStickOn', type: 'REG_SZ', value: '10' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'DockTargetMouseDragOutWidth', type: 'REG_SZ', value: '1' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'DockTargetMouseSideMoveWidth', type: 'REG_SZ', value: '2' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'DockTargetMouseWidth', type: 'REG_SZ', value: '3' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'DockTargetPenDragOutWidth', type: 'REG_SZ', value: '4' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'DockTargetPenSideMoveWidth', type: 'REG_SZ', value: '2' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'DoubleClickHeight2', type: 'REG_SZ', value: '0,7' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'DockTargetPenWidth', type: 'REG_SZ', value: '1' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'ExtendedSounds2', type: 'REG_SZ', value: 'No' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'MouseSensibility2', type: 'REG_SZ', value: '6' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'MouseSpeed2', type: 'REG_SZ', value: '1' },
      ...commonLatencyKeys
    ]
  },
  'ff-precision-pixel-perfect': {
    name: 'FREE FIRE PRECISION 1:1 (Pixel-Perfect & Zero Jitter / Head Lock)',
    fix: '1.0',
    keys: [
      { path: 'HKCU\\Control Panel\\Mouse', name: 'MouseSpeed', type: 'REG_SZ', value: '0' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'MouseThreshold1', type: 'REG_SZ', value: '0' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'MouseThreshold2', type: 'REG_SZ', value: '0' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'MouseSensitivity', type: 'REG_SZ', value: '10' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'MouseHoverTime', type: 'REG_SZ', value: '10' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'SnapToDefaultButton', type: 'REG_SZ', value: '0' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'MouseTrails', type: 'REG_SZ', value: '0' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'SmoothMouseXCurve', type: 'REG_BINARY', value: '0000000000000000156e000000000000004001000000000029dc0300000000000000280000000000ffff0f0000000000' },
      { path: 'HKCU\\Control Panel\\Mouse', name: 'SmoothMouseYCurve', type: 'REG_BINARY', value: '0000000000000000fd11010000000000002404000000000000fc12000000000000c0bb0100000000000058020000000000' },
      { path: 'HKCU\\Control Panel\\Desktop', name: 'MenuShowDelay', type: 'REG_SZ', value: '0' },
      { path: 'HKCU\\Control Panel\\Desktop', name: 'ForegroundLockTimeout', type: 'REG_DWORD', value: 0 },
      { path: 'HKCU\\Control Panel\\Desktop', name: 'ForegroundFlashCount', type: 'REG_DWORD', value: 0 },
      { path: 'HKCU\\System\\GameConfigStore', name: 'GameDVR_Enabled', type: 'REG_DWORD', value: 0 },
      { path: 'HKCU\\System\\GameConfigStore', name: 'GameDVR_FSEBehaviorMode', type: 'REG_DWORD', value: 2 },
      { path: 'HKCU\\System\\GameConfigStore', name: 'GameDVR_HonorUserFSEBehaviorMode', type: 'REG_DWORD', value: 1 },
      { path: 'HKCU\\System\\GameConfigStore', name: 'GameDVR_DXGIHonorFSEWindowsCompatible', type: 'REG_DWORD', value: 1 },
      { path: 'HKCU\\System\\GameConfigStore', name: 'GameDVR_EFSEFeatureFlags', type: 'REG_DWORD', value: 0 },
      { path: 'HKCU\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\GameDVR', name: 'AppCaptureEnabled', type: 'REG_DWORD', value: 0 },
      { path: 'HKCU\\Software\\Microsoft\\GameBar', name: 'AutoGameModeEnabled', type: 'REG_DWORD', value: 1 },
      { path: 'HKCU\\Software\\Microsoft\\GameBar', name: 'AllowAutoGameMode', type: 'REG_DWORD', value: 1 },
      { path: 'HKCU\\Software\\Microsoft\\GameBar', name: 'UseNexusForGameBarEnabled', type: 'REG_DWORD', value: 0 },
      { path: 'HKLM\\SYSTEM\\CurrentControlSet\\Services\\USB', name: 'DisableSelectiveSuspend', type: 'REG_DWORD', value: 1 },
      { path: 'HKLM\\SYSTEM\\CurrentControlSet\\Services\\mouclass\\Parameters', name: 'MouseDataQueueSize', type: 'REG_DWORD', value: 100 },
      { path: 'HKLM\\SYSTEM\\CurrentControlSet\\Services\\kbdclass\\Parameters', name: 'KeyboardDataQueueSize', type: 'REG_DWORD', value: 100 },
      { path: 'HKLM\\SYSTEM\\CurrentControlSet\\Control\\PriorityControl', name: 'IRQ8Priority', type: 'REG_DWORD', value: 1 },
      { path: 'HKLM\\SYSTEM\\CurrentControlSet\\Control\\PriorityControl', name: 'Win32PrioritySeparation', type: 'REG_DWORD', value: 38 },
      { path: 'HKLM\\SYSTEM\\CurrentControlSet\\Control\\Session Manager\\Kernel', name: 'GlobalTimerResolutionRequests', type: 'REG_DWORD', value: 1 },
      { path: 'HKLM\\SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Multimedia\\SystemProfile', name: 'SystemResponsiveness', type: 'REG_DWORD', value: 0 },
      { path: 'HKLM\\SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Multimedia\\SystemProfile', name: 'NetworkThrottlingIndex', type: 'REG_DWORD', value: 4294967295 },
      { path: 'HKLM\\SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Multimedia\\SystemProfile\\Tasks\\Games', name: 'GPU Priority', type: 'REG_DWORD', value: 8 },
      { path: 'HKLM\\SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Multimedia\\SystemProfile\\Tasks\\Games', name: 'Priority', type: 'REG_DWORD', value: 6 },
      { path: 'HKLM\\SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Multimedia\\SystemProfile\\Tasks\\Games', name: 'Scheduling Category', type: 'REG_SZ', value: 'High' },
      { path: 'HKLM\\SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Multimedia\\SystemProfile\\Tasks\\Games', name: 'SFIO Priority', type: 'REG_SZ', value: 'High' },
      ...commonLatencyKeys
    ]
  }
};
